name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fd805d728769fff25259409e78d82d2e80eb00cbf3f5bc6bc1c0b132f2b0622"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
