name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40431d8feca914e02bed0730936fb164ea540bc00086d528eca08d31c2e92343"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
