name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "562c297c7e98540eca741477a94ac87b854c5f7870b3006481388b1ebfb9b469"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
