Platform.mods.kubejs.name = 'Bamsy Mod'

StartupEvents.registry('block', event => {
  event.create('arcane_essence_ore')
    .displayName('Arcane Ore')
    .soundType('nether_ore')
    .hardness(3)
    .resistance(2)
    .tagBlock('forge:ores/arcane_essence')
    .requiresTool(true)
    .tagBlock('forge:ores')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
  event.create('blaze_rod_block')
    .displayName('Block of Blaze Rod')
    .soundType('nether_ore')
    .hardness(3)
    .resistance(2)
    .requiresTool(true)
    .tagBlock('forge:ores')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wood_tool')
    .tagBlock('forge:storage_blocks')
  event.create('book_block')
    .displayName('Block of Books')
    .texture(Direction.DOWN, 'kubejs:block/block_book_down')
    .texture(Direction.UP, 'kubejs:block/block_book_up')
    .texture(Direction.SOUTH, 'kubejs:block/block_book_side')
    .texture(Direction.NORTH, 'kubejs:block/block_book_side')
    .texture(Direction.WEST, 'kubejs:block/block_book_side')
    .texture(Direction.EAST, 'kubejs:block/block_book_side')
    .texture('particle', 'minecraft:book')
    .soundType('wood')
    .hardness(2)
    .resistance(1)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/axe')
    .tagBlock('minecraft:needs_wood_tool')
    .tagBlock('forge:storage_blocks')
})


StartupEvents.registry('item', event => {
  event.create('arcane_shard')
  .displayName('Arcane Shard')
  .tooltip('This is a shard, seems it needs to be processed further...')
  .rarity('rare')
  .glow(true)
  .maxStackSize(64)
  event.create('toilet_paper')
  .displayName('Toilet Paper')
  .tooltip('This is a roll of toilet paper, it is pristine.')
  .rarity('common')
  .maxStackSize(64)
  event.create('bloody_toilet_paper')
  .displayName('Bloody Toilet Paper')
  .tooltip('This is a roll of bloody toilet paper, it`s soaked...')
  .rarity('uncommon')
  .maxStackSize(64)
  event.create('slimy_toilet_paper')
  .displayName('Slimy Toilet Paper')
  .tooltip('This is a roll of slime coated toilet paper, it`s soaked but doesn`t drip...')
  .rarity('rare')
  .maxStackSize(64)
})
